### ISSUE TITLE
jdk 1.7 maven 3.1.1 跑不起来(mvn clean compile)

### ISSUE THREAD

**Issue by tzHome** [v5tech/maven-framework-project#1]
[ERROR] Failed to execute goal on project maven-framework: Could not resolve dependencies for project com.fengjing.framework:maven-framework:war:0.0.1: The following artifacts could not be resolved: log4jdbc:log4jdbc:jar:1.2, org.directwebremoting:dwr:jar:3.0, org.apache.ibatis:ibatis:jar:2.3.4.726: Failure to find log4jdbc:log4jdbc:jar:1.2 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by v5tech** [comment]
请认真阅读3rd目录下的README文件，你需要将该目录中的jar安装到你的maven私服中，因为项目中用到了一些第三方jar，而这些jar在maven的中央仓库中是不存在的（比如oracle数据库的驱动等），所以需要你手动添加到私服中去构建。
